
name: Deploy in kubernetes

on:
  push:
    branches: [ Hometask_8 ]
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    # - name: Checkout source code
    #   run: cd .. && ls -la && pwd
    # env:
    #   workdir-directory: ./SergeyLadutko/Hometask_8/
    # steps:
    # - uses: actions/checkout@master
    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     command: test ./SergeyLadutko/Hometask_8/
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build ./SergeyLadutko/Hometask_8/ --file Dockerfile --tag sergeyladutko/kuber:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push sergeyladutko/kuber:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build ./SergeyLadutko/Hometask_8/ --file Dockerfile --tag sergeyladutko/kuber:latest
    - name: Push the latest Docker image
      run: docker push sergeyladutko/kuber::latest
    # - name: Publish to Registry
    #   uses: docker/build-push-action@v1
    #   # run: ls -la && pwd
    #   with:
    #     repository: sergeyladutko/kuber
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     tags: latest
    #     DOCKERFILE: SergeyLadutko/Hometask_8/Dockerfile
    #     path: SergeyLadutko/Hometask_8/
    #     dockerfile: Dockerfile

