
name: Deploy in kubernetes

on:
  push:
    branches: [ Hometask_8 ]
    
jobs:
  deploy:
    name: test snyk
    runs-on: ubuntu-18.04
    env:
      workdir-directory: ./SergeyLadutko/Hometask_8/
    steps:
    # - uses: actions/checkout@master
    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     command: test ./SergeyLadutko/Hometask_8/
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sergeyladutko/kuber
        workdir-directory: ${{ env.workdir-directory }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # workdir: ./SergeyLadutko/Hometask_8/
        # dockerfile: Dockerfile


