
name: Deploy in kubernetes

on:
  push:
    branches: [ Hometask_8 ]
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout source code
      run: cd .. && ls -la && pwd
    env:
      workdir-directory: ./SergeyLadutko/Hometask_8/
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test ./SergeyLadutko/Hometask_8/

    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: tag
      run: |
        TAG=`echo $GITHUB_REF| sed 's/\//\ /g' | awk '{print $3}'`
        echo $TAG
        sed -i  "s|latest|"$TAG"|g" SergeyLadutko/Hometask_8/kubernetes/deployment.yml
        cat ./SergeyLadutko/Hometask_8/kubernetes/deployment.yml
    - name: Build the tagged Docker image
      run: docker build -t sergeyladutko/kuber:TAG ./SergeyLadutko/Hometask_8/

    - name: Push the tagged Docker image
      run: docker push sergeyladutko/kuber:latest

    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pod
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: apply -f ./SergeyLadutko/Hometask_8/kubernetes/deployment.yml

 