
name: Deploy in kubernetes

on:
  push:
    branches: [ Hometask_8 ]
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout source code
    - uses: actions/checkout@v1
      run: ls
    # env:
    #   workdir-directory: ./SergeyLadutko/Hometask_8/
    # steps:
    # - uses: actions/checkout@master
    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     command: test ./SergeyLadutko/Hometask_8/

    # - name: Publish to Registry
    #   uses: docker/build-push-action@v1
    #   with:
    #     repository: sergeyladutko/kuber
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     tags: latest
    #     path: ./SergeyLadutko/Hometask_8/Dockerfile

